# Default initial positions for ArmsnHands's ros2_control fake system

initial_positions:
  l_forearm_roll_joint: 0
  l_forearm_ud_joint: 0
  l_shoulder_io_joint: 0
  l_shoulder_ud_joint: 0
  l_upper_arm_roll_joint: 0
  r_forearm_roll_joint: 0
  r_forearm_ud_joint: 0
  r_shoulder_io_joint: 0
  r_shoulder_ud_joint: 0
  r_upper_arm_roll_joint: 0