# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - l_shoulder_ud_joint
      - l_shoulder_io_joint
      - l_upper_arm_roll_joint
      - l_forearm_ud_joint
      - l_forearm_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - r_shoulder_ud_joint
      - r_shoulder_io_joint
      - r_upper_arm_roll_joint
      - r_forearm_ud_joint
      - r_forearm_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity